version: '3.8'
services:
  postgres:
    image: postgres:11.10-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-julo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-julo}
      - POSTGRES_DB=${POSTGRES_DB:-julo}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  app:
    image: julo-mini-wallet:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONFIG_FILE_PATH: /etc
      CONFIG_ENV: production
      PRODUCTION_CONFIG: |
        server:
          host: 0.0.0.0
          port: 8080
        postgres:
          host: postgres
          port: 5432
          user: julo
          password: julo
          db: julo
          sslMode: disable
    entrypoint: /bin/sh
    command: -c "echo \"$$PRODUCTION_CONFIG\" > /etc/production.yml;/usr/bin/app"
    ports:
      - 80:8080
